import React, { useEffect, useState } from "react";
import Head from "next/head";
import About from "../components/about/About";
import Banner from "../components/banner/Banner";
import Faq from "../components/faq/Faq";
import Feature from "../components/feature/Feature";
import Footer from "../components/footer/Footer";
import Sponsor from "../components/sponsor/Sponsor";
import Portfolio from "../components/portfolio/Portfolio";
import Service from "../components/service/Service";
import Team from "../components/team/Team";
import Testimonial from "../components/testimonial/Testimonial";
import Preloader from "../components/common/Preloader";
import Header from "../components/header/Header";

function Home4() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 3000);
  }, []);
  return (
    <>
      {!loading ? (
        <Preloader style="home4preloader" />
      ) : (
        <>
          <Head>
            <title>Spinner - Corporate nextjs Template</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/icons/favicon4.png" />
          </Head>
          <Header />
          <Banner />
          <Sponsor />
          <About />
          <Service />
          <Portfolio />
          <Feature />
          <Team />
          <Testimonial />
          <Faq />
          <Footer
            footerStyle="style-4"
            footerImage="assets/images/icons/footer4-logo.svg"
          />
        </>
      )}
    </>
  );
}

export default Home4;
